[build]
  command = "vite build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://16aaa305-dbf9-41fc-8f0b-195f9d5bda98-00-1pqx2xcw58xwn.worf.replit.dev/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
